Removed graphql dependency
The`graphql`dependency caused the module clash error
```
Error: Cannot use GraphQLObjectType "__Directive" from another module or realm.
```
I removed the dependency from the required dependencies while maintaining it as a peer dependency